const express=require("express");
const router=express.Router();
const feiFuController=require("../controller/xxbController");
router.get("/totalCoupon.do",feiFuController.totalCoupon);
router.get("/showCoupon.do",feiFuController.showCoupon);
router.get("/personalCenterGetUserInformation.do",feiFuController.personalCenterGetUserInformation);
router.post("/personalCenterSetImg.do",feiFuController.personalCenterSetImg);
router.get("/sendImg.do",feiFuController.sendImg);
router.get("/updateImg.do",feiFuController.imgUpdate);
router.get("/saveNew.do",feiFuController.saveNew);
router.get("/initHelper.do",feiFuController.initHelper);
router.get("/saveHelper.do",feiFuController.saveHelper);
router.get("/deleteHelper.do",feiFuController.deleteHelper);
router.post("/insertRemark.do",feiFuController.insertRemark);
router.get("/initAddress.do",feiFuController.initAddress);
router.get("/deleteAddress.do",feiFuController.deleteAddress);
router.get("/updateDefault.do",feiFuController.updateDefault);
router.get("/resetAddressDefault.do",feiFuController.resetAddressDefault);
router.get("/updateClickDefault.do",feiFuController.updateClickDefault);
router.post("/checkAll.do",feiFuController.checkAll);
router.post("/insertNewAddress.do",feiFuController.insertNewAddress);
router.post("/getUserPassword.do",feiFuController.getUserPassword);
router.get("/updateAnswer.do",feiFuController.updateAnswer);
router.get("/getOrder.do",feiFuController.getOrder);
module.exports=router;